"""added description to Order

Revision ID: 41ee1fc17f78
Revises: ec0c0582f0b8
Create Date: 2024-07-04 20:03:24.712938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ee1fc17f78'
down_revision = 'ec0c0582f0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
