"""Updated order table

Revision ID: 542c23dbcd20
Revises: a0ccebd3614a
Create Date: 2024-06-23 17:03:17.405533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '542c23dbcd20'
down_revision = 'a0ccebd3614a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('item_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('selections', sa.JSON(), nullable=False))
        batch_op.alter_column('scheduled_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('order_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_data', mysql.JSON(), nullable=True))
        batch_op.alter_column('scheduled_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('selections')
        batch_op.drop_column('item_name')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
