"""removed scheduled time from order model

Revision ID: d1d4521899d0
Revises: 41ee1fc17f78
Create Date: 2024-07-19 17:55:21.549163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1d4521899d0'
down_revision = '41ee1fc17f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('scheduled_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_time', mysql.VARCHAR(length=128), nullable=False))

    # ### end Alembic commands ###
