"""changed scheduled_time to a string

Revision ID: ec0c0582f0b8
Revises: 542c23dbcd20
Create Date: 2024-06-23 18:26:04.540043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec0c0582f0b8'
down_revision = '542c23dbcd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('scheduled_time',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('scheduled_time',
               existing_type=sa.String(length=128),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
