"""Changed Column Name in Item table from customization_options to field 

Revision ID: 06fdef09c8b3
Revises: d765a2532bcd
Create Date: 2024-05-08 20:10:59.919772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06fdef09c8b3'
down_revision = 'd765a2532bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fields', sa.JSON(), nullable=True))
        batch_op.drop_column('customization_options')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customization_options', mysql.JSON(), nullable=True))
        batch_op.drop_column('fields')

    # ### end Alembic commands ###
