"""Added lazy querying for active_menu object column to allow easier querying

Revision ID: 20d3ea4bae6d
Revises: 06fdef09c8b3
Create Date: 2024-05-17 18:58:56.833851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20d3ea4bae6d'
down_revision = '06fdef09c8b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_menu_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('meal_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'menu', ['active_menu_id'], ['menu_id'])
        batch_op.drop_column('active_menu')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_menu', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('meal_ibfk_1', 'menu', ['active_menu'], ['menu_id'])
        batch_op.drop_column('active_menu_id')

    # ### end Alembic commands ###
