"""Changed start/end time format 

Revision ID: 50317fe05df2
Revises: 7a71d89f676a
Create Date: 2024-06-15 17:35:19.895139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50317fe05df2'
down_revision = '7a71d89f676a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.String(length=10),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.String(length=10),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
