"""Added user columns related to ordering

Revision ID: 50fceab29c10
Revises: 732a6523c6d5
Create Date: 2024-06-08 07:13:43.181692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50fceab29c10'
down_revision = '732a6523c6d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_details', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('placed_orders', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_k_meals', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('suspended', sa.Boolean(), server_default='0', nullable=False))
        batch_op.drop_column('profile_picture_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_url', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('suspended')
        batch_op.drop_column('last_k_meals')
        batch_op.drop_column('placed_orders')
        batch_op.drop_column('order_details')

    # ### end Alembic commands ###
