"""Renamed special request column to description

Revision ID: 7a71d89f676a
Revises: 50fceab29c10
Create Date: 2024-06-09 18:29:55.997142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a71d89f676a'
down_revision = '50fceab29c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.drop_column('order_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_details', mysql.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
