"""Added order table

Revision ID: 8863eca57e8a
Revises: 3a6298be5a24
Create Date: 2024-05-05 15:55:55.169664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8863eca57e8a'
down_revision = '3a6298be5a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_data', sa.JSON(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
