"""restructured order table

Revision ID: c3420cff9e05
Revises: 50317fe05df2
Create Date: 2024-06-23 16:34:12.760893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3420cff9e05'
down_revision = '50317fe05df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('item_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('selections', sa.JSON(), nullable=False))
        batch_op.drop_column('order_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_data', mysql.JSON(), nullable=True))
        batch_op.drop_column('selections')
        batch_op.drop_column('item_name')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
