"""Created meal, menu, and item tables for handling menus; added default for order scheduled_time

Revision ID: d765a2532bcd
Revises: 8863eca57e8a
Create Date: 2024-05-06 17:52:06.090397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd765a2532bcd'
down_revision = '8863eca57e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('customization_options', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_name'), ['name'], unique=True)

    op.create_table('menu',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('menu_id')
    )
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_name'), ['name'], unique=True)

    op.create_table('meal',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('order_padding', sa.Integer(), server_default='0', nullable=True),
    sa.Column('active_menu', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_menu'], ['menu.menu_id'], name='fk_meal_active_menu_menu_id'),
    sa.PrimaryKeyConstraint('meal_id')
    )
    op.create_table('menu_items',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.menu_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_id', 'item_id')
    )
    op.alter_column('order', 'scheduled_time',
                    existing_type=sa.DateTime(),
                    nullable=False,
                    server_default=sa.text('CURRENT_TIMESTAMP'))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_items')
    op.drop_table('meal')
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_name'))

    op.drop_table('menu')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_name'))

    op.drop_table('item')

    op.alter_column('order', 'scheduled_time',
                existing_type=sa.DateTime(),
                nullable=True, 
                server_default=None) 
    # ### end Alembic commands ###

