"""added meal_date

Revision ID: fb0c7c19d509
Revises: 430f4d0004f1
Create Date: 2024-07-21 17:27:45.396174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb0c7c19d509'
down_revision = '430f4d0004f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_date', sa.Integer(), nullable=False))
        batch_op.alter_column('meal_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('meal_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('meal_date')

    # ### end Alembic commands ###
